import Head from "next/head";
import Image from "next/image";
// import Three from "../components/Three/Three";
import styles from "../styles/Home.module.css";

import Redux from "../components/Redux/Redux";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Three /> */}
        <Redux />
      </main>
    </div>
  );
}
